# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8977bbc2fc790255be6282000c066ef5596e2c8e4971e58014af698776c9589a0d8bcc7449430b879a710f4c1549835886038eba9b8f52ddbafe61178643988a

test:
  secret_key_base: 4b42f1c2cdccd6077f0057b2ecd711b105e349d825a96a089f94cc8486203c3a072c431845f73fc652a2e1429450424fac33706c7f546b57083b45c734ff6600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
